packages:
  - "plugins/*"
  - "!plugins/_template"
  - "addons/*"
  - "storybook/"
  - "adapters/**/*"
catalog:
  "@tiptap/core": "^3.10.1"
  "@tiptap/react": "^3.10.1"
  "@tiptap/pm": "^3.10.1"
  "@tiptap/starter-kit": "^3.10.1"
  "@tiptap/extension-image": "^3.10.1"
catalogs:
  mdast:
    unist-util-visit: "^5.0.0"
    unist-util-visit-parents: "^6.0.2"
    "@types/mdast": "^4.0.4"
    "mdast-util-to-markdown": "^2.1.2"
    "mdast-util-to-string": "^4.0.0"
  storybook:
    "@storybook/addon-vitest": "^10.0.2"
    "@storybook/react-vite": "^10.0.2"
    "storybook": "^10.0.2"
  react:
    "react": "19.1.1"
    "react-dom": "19.1.1"
    "@types/react": "^19.2.2"
    "@types/react-dom": "^19.2.2"
